# Generated by Django 5.0.14 on 2026-05-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpublickey',
            name='algorithm',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
