# Generated by Django 5.0.14 on 2026-05-16 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0002_userpublickey_algorithm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpublickey',
            name='algorithm',
        ),
    ]
