# Generated by Django 5.0.14 on 2026-05-16 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0001_initial'),
        ('courses', '0001_initial'),
        ('evaluations', '0001_initial'),
        ('keys', '0001_initial'),
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecureFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('student_submission', 'Student Submission'), ('rubric', 'Rubric'), ('evaluation_material', 'Evaluation Material'), ('feedback', 'Feedback'), ('ai_evaluation_result', 'AI Evaluation Result'), ('examiner_evaluation', 'Examiner Evaluation')], max_length=64)),
                ('object_storage_key', models.CharField(max_length=512)),
                ('ciphertext_sha256', models.CharField(max_length=64)),
                ('plaintext_sha256', models.CharField(max_length=64)),
                ('aes_gcm_iv', models.TextField()),
                ('aes_gcm_tag', models.TextField()),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('mime_type', models.CharField(max_length=128)),
                ('encrypted_filename', models.JSONField(blank=True, null=True)),
                ('schema_version', models.CharField(default='v1', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='assignments.assignment')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='courses.course')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_files', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='submissions.submission')),
            ],
        ),
        migrations.CreateModel(
            name='FileManifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manifest_json', models.JSONField()),
                ('manifest_sha256', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manifest', to='files.securefile')),
            ],
        ),
        migrations.CreateModel(
            name='EncryptedFileKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrapped_key_algorithm', models.CharField(default='RSA-OAEP-SHA256', max_length=64)),
                ('wrapped_key_ciphertext', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_encrypted_file_keys', to=settings.AUTH_USER_MODEL)),
                ('recipient_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wrapped_file_keys', to='keys.userpublickey')),
                ('recipient_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encrypted_file_keys', to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encrypted_keys', to='files.securefile')),
            ],
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_algorithm', models.CharField(default='RSA-PSS-SHA256', max_length=64)),
                ('signature_value', models.TextField()),
                ('signed_payload_sha256', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='evaluations.evaluation')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='files.securefile')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signatures', to='keys.userpublickey')),
                ('signed_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signatures', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='submissions.submission')),
            ],
        ),
        migrations.AddIndex(
            model_name='securefile',
            index=models.Index(fields=['course', 'assignment', 'file_type'], name='files_secur_course__343ba2_idx'),
        ),
        migrations.AddIndex(
            model_name='securefile',
            index=models.Index(fields=['submission', 'file_type'], name='files_secur_submiss_0065df_idx'),
        ),
        migrations.AddIndex(
            model_name='securefile',
            index=models.Index(fields=['ciphertext_sha256'], name='files_secur_ciphert_96b47d_idx'),
        ),
        migrations.AddIndex(
            model_name='encryptedfilekey',
            index=models.Index(fields=['file', 'recipient_user', 'revoked_at'], name='files_encry_file_id_892e0b_idx'),
        ),
    ]
