# Generated by Django 5.0.14 on 2026-05-16 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='description_ciphertext',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='rubric_release_at',
        ),
        migrations.AddField(
            model_name='assignment',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='submission_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
