class EncryptedObjectStore:
    """Storage boundary for ciphertext blobs.

    Implementations must never accept plaintext. Object keys should be opaque,
    non-guessable identifiers generated by the backend.
    """

    def create_upload_target(self, *, content_length: int, content_type: str) -> dict:
        raise NotImplementedError("Object storage upload targets are not implemented in the scaffold.")

    def create_download_target(self, *, object_storage_key: str) -> dict:
        raise NotImplementedError("Object storage download targets are not implemented in the scaffold.")

